# Site settings
title: "Developer Senpai"
description: > 
  Anime is better with Android, tf?

author: Ashish Kharche Senpai
email: developersenpai@gmail.com
twitter_username: _HairForceOne
github_username: developersenpai

#baseurl: "/paper-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://developersenpai.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

